name: sysfoo-ci-pipeline
on:
  push:
    branches:
      - 'master'
jobs:
  sysfooci-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'welcome to sysfoo application'
        
      - name: code-checkout
        uses: actions/checkout@v6
        
      - name: mvn-test
        run: mvn test
        
      - name: mvn-package-clean
        run: mvn clean
        
      - name: mvn-package
        run: mvn package

      - name: list-files
        run: ls -lrt target

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysfoo-artifact
          path: target/**.war

      - name: download-artifact
        uses: actions/download-artifact@v5
        with:
          name: sysfoo-artifact
          path: C:/Users/kkzh451/Downloads
      - name: Display structure of downloaded files
        run: ls -R C:/Users/kkzh451/Downloads
  
